### ISSUE TITLE
cloudformation.iam: Fail to parse yaml list with empty lines

### ISSUE THREAD

**Issue by Gellardo** [aquasecurity/defsec#302]
### Given
A bigger cloudformation file in a repo. I minimized it down quite a bit (until it makes no semantic sense anymore).

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ECSRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: ecs-service
          PolicyDocument:
            Statement:
              - Action:
                  - 'ec2:AttachNetworkInterface'

                  - 'ec2:CreateNetworkInterface'
```

### Expected

Parsing to succeed if it is valid yaml.

### Actual

Parsing failure due to the empty line in the `Action` list.

```
$ trivy filesystem .
panic: runtime error: slice bounds out of range [12:0]

goroutine 1 [running]:
github.com/aquasecurity/defsec/parsers/cloudformation/parser.removeLeftMargin({0xc0007b06a0, 0x5, 0x6})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.12.1/parsers/cloudformation/parser/property.go:368 +0xe5
github.com/aquasecurity/defsec/parsers/cloudformation/parser.(*Property).GetJsonBytes(0xc0007bc480, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.12.1/parsers/cloudformation/parser/property.go:342 +0xfa
github.com/aquasecurity/defsec/adapters/cloudformation/aws/iam.getPoliciesDocs(0xc0006140a0)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.12.1/adapters/cloudformation/aws/iam/policy.go:80 +0xe8
github.com/aquasecurity/defsec/adapters/cloudformation/aws/iam.getRoles({{0xc00004f5c0, 0x54}, {0xc0007b0620, 0xe, 0xe}, {0x28ca890, 0x4}, 0x0, 0xc00055aff0, 0x0, ...})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.12.1/adapters/cloudformation/aws/iam/policy.go:39 +0x259
github.com/aquasecurity/defsec/adapters/cloudformation/aws/iam.Adapt({{0xc00004f5c0, 0x54}, {0xc0007b0620, 0xe, 0xe}, {0x28ca890, 0x4}, 0x0, 0xc00055aff0, 0x0, ...})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.12.1/adapters/cloudformation/aws/iam/iam.go:12 +0xb8
github.com/aquasecurity/defsec/adapters/cloudformation/aws.Adapt({{0xc00004f5c0, 0x54}, {0xc0007b0620, 0xe, 0xe}, {0x28ca890, 0x4}, 0x0, 0xc00055aff0, 0x0, ...})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.12.1/adapters/cloudformation/aws/adapt.go:61 +0xb98
github.com/aquasecurity/defsec/adapters/cloudformation.Adapt(...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.12.1/adapters/cloudformation/adapt.go:12
github.com/aquasecurity/defsec/scanners/cloudformation/scanner.(*Scanner).Scan(0xc000614b90)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.12.1/scanners/cloudformation/scanner/scanner.go:95 +0x138
github.com/aquasecurity/fanal/config/scanner.Scanner.scanCloudFormation({{0x7ffeefbfef79, 0x1}, {0x0, 0x0, 0x0}, 0x0, 0xc000c7e8c0, 0xc000614b90}, {0xc00055acc0, 0x1, ...})
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220225095822-ef150f781751/config/scanner/scanner.go:151 +0x297
github.com/aquasecurity/fanal/config/scanner.Scanner.ScanConfigs({{0x7ffeefbfef79, 0x1}, {0x0, 0x0, 0x0}, 0x0, 0xc000c7e8c0, 0xc000614b90}, {0x2d5a098, 0xc000051bc0}, ...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220225095822-ef150f781751/config/scanner/scanner.go:97 +0x465
github.com/aquasecurity/fanal/artifact/local.Artifact.Inspect({{0x7ffeefbfef79, 0x1}, {0x2bef8038, 0xc0004cc1c0}, {{{0x0, 0x0, 0x0}, {0xc000c92000, 0x3, 0x4}}}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220225095822-ef150f781751/artifact/local/fs.go:115 +0x345
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact({{_, _}, {_, _}}, {_, _}, {{0xc000c88720, 0x2, 0x2}, {0xc0004cc100, ...}, ...})
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:94 +0xce
github.com/aquasecurity/trivy/pkg/commands/artifact.scan({_, _}, {{0xc000c05e00, 0xc0006a83c8, {0x2cff304, 0x6}, 0x0, 0x0, {0xc0008d6de0, 0x21}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:217 +0x8fe
github.com/aquasecurity/trivy/pkg/commands/artifact.runWithTimeout({_, _}, {{0xc000c05e00, 0xc0006a83c8, {0x2cff304, 0x6}, 0x0, 0x0, {0xc0008d6de0, 0x21}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:68 +0x44c
github.com/aquasecurity/trivy/pkg/commands/artifact.Run({_, _}, {{0xc000c05e00, 0xc0006a83c8, {0x2cff304, 0x6}, 0x0, 0x0, {0xc0008d6de0, 0x21}}, ...}, ...)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:40 +0xca
github.com/aquasecurity/trivy/pkg/commands/artifact.FilesystemRun(0xc000c05e00)
        /home/runner/work/trivy/trivy/pkg/commands/artifact/fs.go:35 +0x1a6
github.com/urfave/cli/v2.(*Command).Run(0xc0003c3320, 0xc000c05500)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc000603a00, {0x2d5a060, 0xc0000440c0}, {0xc00003a0c0, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/runner/work/trivy/trivy/cmd/trivy/main.go:16 +0x4f

shell returned 2
```

Initial investigation:

- Comments do not influence this error, since any comment line seems to be filtered out beforehand.
- Any line which only contains less spaces than the first line of the list leads to the same failure.

- Same problem occurs if I add a second Action object with a preceding empty line.
- This does **not** happen if I add a second Policy object with a preceding empty line.

**Comment by Gellardo** [comment]
Same problem with other Properties, e.g.

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image: docker.io/mongo:4

        - Image: docker.io/mongo:4
```

**Comment by Gellardo** [comment]
still applies

**Comment by liamg** [comment]
We've just merged a fix for this, should be available in trivy soon.
